In [1]:
import numpy as np

In [2]:
#1. What is a Python library? Why ^o we use Python libraries?

print('A Python library is a collection of Python modules and packages that are pre-written and can be used in Python programs. They are used to extend the functionality of the Python programming language and make it easier to write specific types of programs.')
print('We use Python libraries because they save us time and effort by providing us with pre-written code that we can use in our own programs. They also allow us to access a wide range of functionality that would be difficult or impossible to implement on our own.')


A Python library is a collection of Python modules and packages that are pre-written and can be used in Python programs. They are used to extend the functionality of the Python programming language and make it easier to write specific types of programs.
We use Python libraries because they save us time and effort by providing us with pre-written code that we can use in our own programs. They also allow us to access a wide range of functionality that would be difficult or impossible to implement on our own.


In [3]:
#2. What is the ^ifference between Numpy array an^ List?

print('A NumPy array is a multidimensional array of numbers, while a list is a one-dimensional array of objects. NumPy arrays are more efficient than lists for storing and processing large amounts of data, and they have a number of features that make them easier to use for scientific computing.')
print('Here are some of the key differences between NumPy arrays and lists:')

print('Data type: NumPy arrays can store numbers of different data types, while lists can only store objects.')
print('Size: NumPy arrays can be of any size, while lists are limited to a maximum size of 2**31 - 1 elements.')
print('Memory efficiency: NumPy arrays are stored in contiguous memory locations, which makes them more efficient to access than lists.')
print('Speed: NumPy arrays are optimized for scientific computing, and they can be processed much faster than lists.')
print('Features: NumPy arrays have a number of features that make them easier to use for scientific computing, such as support for linear algebra, statistics, and signal processing.')


A NumPy array is a multidimensional array of numbers, while a list is a one-dimensional array of objects. NumPy arrays are more efficient than lists for storing and processing large amounts of data, and they have a number of features that make them easier to use for scientific computing.
Here are some of the key differences between NumPy arrays and lists:
Data type: NumPy arrays can store numbers of different data types, while lists can only store objects.
Size: NumPy arrays can be of any size, while lists are limited to a maximum size of 2**31 - 1 elements.
Memory efficiency: NumPy arrays are stored in contiguous memory locations, which makes them more efficient to access than lists.
Speed: NumPy arrays are optimized for scientific computing, and they can be processed much faster than lists.
Features: NumPy arrays have a number of features that make them easier to use for scientific computing, such as support for linear algebra, statistics, and signal processing.


In [8]:
#3. 3. Find the shape, size and dimension of the following array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Shape:', arr.shape)  # (3, 4)
print('Size:', arr.size)  # 12
print('Dimension:', arr.ndim)  # 2


Shape: (3, 4)
Size: 12
Dimension: 2


In [7]:
#4. Write python code to access the first row of the following array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0])  # [1, 2, 3, 4]


[1 2 3 4]


In [9]:
#5. How do you access the element at the third row and fourth column from the given numpy array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[2, 3])  # 12


12


In [10]:
#6. Write code to extract all odd-indexed elements from the given numpy array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_elements = arr[1::2]
print(odd_elements)  # [3, 7, 11]


[[5 6 7 8]]


In [11]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?


# Generate a random 3x3 matrix with values between 0 and 1
rand_matrix = np.random.rand(3, 3)
print(rand_matrix)


[[0.52137516 0.12368545 0.98799826]
 [0.80091032 0.40358324 0.26212107]
 [0.58260312 0.9561177  0.87854791]]


In [12]:
#8. Describe the difference between np.random.rand and np.random.randn?

# np.random.rand() generates random floats between 0 and 1
rand_values = np.random.rand(10)
print(rand_values)

# np.random.randn() generates random floats with a mean of 0 and a standard deviation of 1
randn_values = np.random.randn(10)
print(randn_values)


[0.09925559 0.28249047 0.58232065 0.39347194 0.2910446  0.58313821
 0.10912801 0.44277305 0.45093775 0.2664894 ]
[-0.99130294  1.12148013 -0.91407986 -0.07811415 -0.04866499 -1.25114122
 -0.04068106  0.69779343 -0.95783989  0.70191305]


In [13]:
#9. Write code to increase the dimension of the following array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)  # (3, 4)

# Increase the dimension of the array by adding a new axis at the beginning
new_arr = np.expand_dims(arr, axis=0)
print(new_arr.shape)  # (1, 3, 4)


(3, 4)
(1, 3, 4)


In [14]:
#10. How to transpose the following array in NumPy? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.T)  # [[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
